### PR TITLE
Create quiz.cpp

### PR DESCRIPTION
**Pull request by joeljustin1**
It is a quiz project which chooses random questions from a larger set of questions. The questions are mostly science based.

### CODE REVIEW

**Comment by viralvaghela** [comment]
good work @joeljustin1

**Comment by viralvaghela** [comment]
Sorry,that was closed by mistake :(

**Comment by joeljustin1** [comment]
Thanks a lot. So Happy to see you recognize my project.

Joel Justin

**Comment by viralvaghela** [comment]
keep doing great work @joeljustin1  :)

**Pull request merged**
